env:
  browser: true
  commonjs: true
  node: true
  es6: true
  mocha: true
extends: 
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:vue/essential'
parserOptions:
  ecmaFeatures:
    ecmaVersion: 6
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - jasmine
  - mocha 
  - vue
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - single 
    - allowTemplateLiterals: true
  semi: 1
  no-console: 1
  "react/prop-types": [1, { ignore: ["children", "data"] }]
  "vue/max-attributes-per-line": [2]
  space-in-parens:
    - 0
    - never
globals:
  angular: true
  graphql: true
  uirouter: true
  proto: true
